feature(REPORT-332970): Update package details
boldreports/javascript-samples pull request #30
Opened 2023-11-08 11:35 UTC by SundaresanGunasekaran

<table>
<tr>
<td>
Description:
</td>
<td>
Update package details
</td>
</tr>
<tr>
<td>
Analysis:
</td>
<td>
Analyzed about Update package details
</td>
</tr>
<tr>
<td>
Reason for not identifying earlier:
</td>
<td>
It's a new feature
</td>
</tr>
<tr>
<td>
Is it a breaking issue?
</td>
<td>
No, It's a new feature
</td>
</tr>
<tr>
<td>
Solution description:
</td>
<td>
Update package details
</td>
</tr>
<tr>
<td>
Areas affected and ensured:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test cases:
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Test bed sample location:
</td>
<td>
VS & VS Code
</td>
</tr>
</table>

2023-11-08 15:42 UTC, karthickthangasamy requested changes

2023-11-08 15:42 UTC, karthickthangasamy commented on src/controls/globals.js
> -    SERVICE_URL: 'https://demos.boldreports.com/services/api/ReportViewerWebApi',
revert this changes

2023-11-09 04:23 UTC, SundaresanGunasekaran commented on src/controls/globals.js
> -    SERVICE_URL: 'https://demos.boldreports.com/services/api/ReportViewerWebApi',
Done

2023-11-09 04:45 UTC, karthickthangasamy approved these changes

2023-11-09 04:45 UTC, merged